---
dependencies:
- name: "infrastructure"
  repository: "https://activiti.github.io/activiti-cloud-helm-charts/"
  version: "0.0.13"
- name: "application"
  repository: "https://activiti.github.io/activiti-cloud-helm-charts/"
  version: "0.0.105"
- name: "activiti-cloud-modeling"
  repository: "https://activiti.github.io/activiti-cloud-helm-charts/"
  version: "7.0.35"  
