---
dependencies:
- name: "infrastructure"
  repository: "https://activiti.github.io/activiti-cloud-helm-charts/"
  version: "0.0.24"
- name: "application"
  repository: "https://activiti.github.io/activiti-cloud-helm-charts/"
  version: "0.0.182"
- name: "activiti-cloud-modeling"
  repository: "https://activiti.github.io/activiti-cloud-helm-charts/"
  version: "7.1.79"
